import React from "react";

const citys = [
  { city: "Medellín", department: "Antioquia" },
  { city: "Abejorral", department: "Antioquia" },
  { city: "Abriaquí", department: "Antioquia" },
  { city: "Alejandría", department: "Antioquia" },
  { city: "Amagá", department: "Antioquia" },
  { city: "Amalfi", department: "Antioquia" },
  { city: "Andes", department: "Antioquia" },
  { city: "Angelópolis", department: "Antioquia" },
  { city: "Angostura", department: "Antioquia" },
  { city: "Anorí", department: "Antioquia" },
  { city: "Tununguá", department: "Boyacá" },
  { city: "Anza", department: "Antioquia" },
  { city: "Apartadó", department: "Antioquia" },
  { city: "Arboletes", department: "Antioquia" },
  { city: "Argelia", department: "Antioquia" },
  { city: "Armenia", department: "Antioquia" },
  { city: "Barbosa", department: "Antioquia" },
  { city: "Bello", department: "Antioquia" },
  { city: "Betania", department: "Antioquia" },
  { city: "Betulia", department: "Antioquia" },
  { city: "Ciudad Bolívar", department: "Antioquia" },
  { city: "Briceño", department: "Antioquia" },
  { city: "Buriticá", department: "Antioquia" },
  { city: "Cáceres", department: "Antioquia" },
  { city: "Caicedo", department: "Antioquia" },
  { city: "Caldas", department: "Antioquia" },
  { city: "Campamento", department: "Antioquia" },
  { city: "Cañasgordas", department: "Antioquia" },
  { city: "Caracolí", department: "Antioquia" },
  { city: "Caramanta", department: "Antioquia" },
  { city: "Carepa", department: "Antioquia" },
  { city: "Motavita", department: "Boyacá" },
  { city: "Carolina", department: "Antioquia" },
  { city: "Caucasia", department: "Antioquia" },
  { city: "Chigorodó", department: "Antioquia" },
  { city: "Cisneros", department: "Antioquia" },
  { city: "Cocorná", department: "Antioquia" },
  { city: "Concepción", department: "Antioquia" },
  { city: "Concordia", department: "Antioquia" },
  { city: "Copacabana", department: "Antioquia" },
  { city: "Dabeiba", department: "Antioquia" },
  { city: "Don Matías", department: "Antioquia" },
  { city: "Ebéjico", department: "Antioquia" },
  { city: "El Bagre", department: "Antioquia" },
  { city: "Entrerrios", department: "Antioquia" },
  { city: "Envigado", department: "Antioquia" },
  { city: "Fredonia", department: "Antioquia" },
  { city: "San Bernardo del Viento", department: "Córdoba" },
  { city: "Giraldo", department: "Antioquia" },
  { city: "Girardota", department: "Antioquia" },
  { city: "Gómez Plata", department: "Antioquia" },
  { city: "Istmina", department: "Chocó" },
  { city: "Guadalupe", department: "Antioquia" },
  { city: "Guarne", department: "Antioquia" },
  { city: "Guatapé", department: "Antioquia" },
  { city: "Heliconia", department: "Antioquia" },
  { city: "Hispania", department: "Antioquia" },
  { city: "Itagui", department: "Antioquia" },
  { city: "Ituango", department: "Antioquia" },
  { city: "Belmira", department: "Antioquia" },
  { city: "Jericó", department: "Antioquia" },
  { city: "La Ceja", department: "Antioquia" },
  { city: "La Estrella", department: "Antioquia" },
  { city: "La Pintada", department: "Antioquia" },
  { city: "La Unión", department: "Antioquia" },
  { city: "Liborina", department: "Antioquia" },
  { city: "Maceo", department: "Antioquia" },
  { city: "Marinilla", department: "Antioquia" },
  { city: "Montebello", department: "Antioquia" },
  { city: "Murindó", department: "Antioquia" },
  { city: "Mutatá", department: "Antioquia" },
  { city: "Nariño", department: "Antioquia" },
  { city: "Necoclí", department: "Antioquia" },
  { city: "Nechí", department: "Antioquia" },
  { city: "Olaya", department: "Antioquia" },
  { city: "Peñol", department: "Antioquia" },
  { city: "Peque", department: "Antioquia" },
  { city: "Pueblorrico", department: "Antioquia" },
  { city: "Puerto Berrío", department: "Antioquia" },
  { city: "Puerto Nare", department: "Antioquia" },
  { city: "Puerto Triunfo", department: "Antioquia" },
  { city: "Remedios", department: "Antioquia" },
  { city: "Retiro", department: "Antioquia" },
  { city: "Rionegro", department: "Antioquia" },
  { city: "Sabanalarga", department: "Antioquia" },
  { city: "Sabaneta", department: "Antioquia" },
  { city: "Salgar", department: "Antioquia" },
  { city: "Ciénega", department: "Boyacá" },
  { city: "Santacruz", department: "Nariño" },
  { city: "San Francisco", department: "Antioquia" },
  { city: "San Jerónimo", department: "Antioquia" },
  { city: "Puerto Wilches", department: "Santander" },
  { city: "Puerto Parra", department: "Santander" },
  { city: "San Luis", department: "Antioquia" },
  { city: "San Pedro", department: "Antioquia" },
  { city: "San Rafael", department: "Antioquia" },
  { city: "San Roque", department: "Antioquia" },
  { city: "San Vicente", department: "Antioquia" },
  { city: "Santa Bárbara", department: "Antioquia" },
  { city: "Santo Domingo", department: "Antioquia" },
  { city: "El Santuario", department: "Antioquia" },
  { city: "Segovia", department: "Antioquia" },
  { city: "Sopetrán", department: "Antioquia" },
  { city: "Uribe", department: "Meta" },
  { city: "Támesis", department: "Antioquia" },
  { city: "Tarazá", department: "Antioquia" },
  { city: "Tarso", department: "Antioquia" },
  { city: "Titiribí", department: "Antioquia" },
  { city: "Toledo", department: "Antioquia" },
  { city: "Turbo", department: "Antioquia" },
  { city: "Uramita", department: "Antioquia" },
  { city: "Urrao", department: "Antioquia" },
  { city: "Valdivia", department: "Antioquia" },
  { city: "Valparaíso", department: "Antioquia" },
  { city: "Vegachí", department: "Antioquia" },
  { city: "Venecia", department: "Antioquia" },
  { city: "Yalí", department: "Antioquia" },
  { city: "Yarumal", department: "Antioquia" },
  { city: "Yolombó", department: "Antioquia" },
  { city: "Yondó", department: "Antioquia" },
  { city: "Zaragoza", department: "Antioquia" },
  { city: "Barranquilla", department: "Atlántico" },
  { city: "Baranoa", department: "Atlántico" },
  { city: "Candelaria", department: "Atlántico" },
  { city: "Galapa", department: "Atlántico" },
  { city: "Luruaco", department: "Atlántico" },
  { city: "Malambo", department: "Atlántico" },
  { city: "Manatí", department: "Atlántico" },
  { city: "Piojó", department: "Atlántico" },
  { city: "Polonuevo", department: "Atlántico" },
  { city: "Sabanagrande", department: "Atlántico" },
  { city: "Sabanalarga", department: "Atlántico" },
  { city: "Santa Lucía", department: "Atlántico" },
  { city: "Santo Tomás", department: "Atlántico" },
  { city: "Soledad", department: "Atlántico" },
  { city: "Suan", department: "Atlántico" },
  { city: "Tubará", department: "Atlántico" },
  { city: "Usiacurí", department: "Atlántico" },
  { city: "Achí", department: "Bolívar" },
  { city: "Arenal", department: "Bolívar" },
  { city: "Arjona", department: "Bolívar" },
  { city: "Arroyohondo", department: "Bolívar" },
  { city: "Calamar", department: "Bolívar" },
  { city: "Cantagallo", department: "Bolívar" },
  { city: "Cicuco", department: "Bolívar" },
  { city: "Córdoba", department: "Bolívar" },
  { city: "Clemencia", department: "Bolívar" },
  { city: "El Guamo", department: "Bolívar" },
  { city: "Magangué", department: "Bolívar" },
  { city: "Mahates", department: "Bolívar" },
  { city: "Margarita", department: "Bolívar" },
  { city: "Montecristo", department: "Bolívar" },
  { city: "Mompós", department: "Bolívar" },
  { city: "Morales", department: "Bolívar" },
  { city: "Norosí", department: "Bolívar" },
  { city: "Pinillos", department: "Bolívar" },
  { city: "Regidor", department: "Bolívar" },
  { city: "Río Viejo", department: "Bolívar" },
  { city: "San Estanislao", department: "Bolívar" },
  { city: "San Fernando", department: "Bolívar" },
  { city: "San Juan Nepomuceno", department: "Bolívar" },
  { city: "Santa Catalina", department: "Bolívar" },
  { city: "Santa Rosa", department: "Bolívar" },
  { city: "Simití", department: "Bolívar" },
  { city: "Soplaviento", department: "Bolívar" },
  { city: "Talaigua Nuevo", department: "Bolívar" },
  { city: "Tiquisio", department: "Bolívar" },
  { city: "Turbaco", department: "Bolívar" },
  { city: "Turbaná", department: "Bolívar" },
  { city: "Villanueva", department: "Bolívar" },
  { city: "Tunja", department: "Boyacá" },
  { city: "Almeida", department: "Boyacá" },
  { city: "Aquitania", department: "Boyacá" },
  { city: "Arcabuco", department: "Boyacá" },
  { city: "Berbeo", department: "Boyacá" },
  { city: "Betéitiva", department: "Boyacá" },
  { city: "Boavita", department: "Boyacá" },
  { city: "Boyacá", department: "Boyacá" },
  { city: "Briceño", department: "Boyacá" },
  { city: "Buena Vista", department: "Boyacá" },
  { city: "Busbanzá", department: "Boyacá" },
  { city: "Caldas", department: "Boyacá" },
  { city: "Campohermoso", department: "Boyacá" },
  { city: "Cerinza", department: "Boyacá" },
  { city: "Chinavita", department: "Boyacá" },
  { city: "Chiquinquirá", department: "Boyacá" },
  { city: "Chiscas", department: "Boyacá" },
  { city: "Chita", department: "Boyacá" },
  { city: "Chitaraque", department: "Boyacá" },
  { city: "Chivatá", department: "Boyacá" },
  { city: "Cómbita", department: "Boyacá" },
  { city: "Coper", department: "Boyacá" },
  { city: "Corrales", department: "Boyacá" },
  { city: "Covarachía", department: "Boyacá" },
  { city: "Cubará", department: "Boyacá" },
  { city: "Cucaita", department: "Boyacá" },
  { city: "Cuítiva", department: "Boyacá" },
  { city: "Chíquiza", department: "Boyacá" },
  { city: "Chivor", department: "Boyacá" },
  { city: "Duitama", department: "Boyacá" },
  { city: "El Cocuy", department: "Boyacá" },
  { city: "El Espino", department: "Boyacá" },
  { city: "Firavitoba", department: "Boyacá" },
  { city: "Floresta", department: "Boyacá" },
  { city: "Gachantivá", department: "Boyacá" },
  { city: "Gameza", department: "Boyacá" },
  { city: "Garagoa", department: "Boyacá" },
  { city: "Guacamayas", department: "Boyacá" },
  { city: "Guateque", department: "Boyacá" },
  { city: "Guayatá", department: "Boyacá" },
  { city: "Güicán", department: "Boyacá" },
  { city: "Iza", department: "Boyacá" },
  { city: "Jenesano", department: "Boyacá" },
  { city: "Jericó", department: "Boyacá" },
  { city: "Labranzagrande", department: "Boyacá" },
  { city: "La Capilla", department: "Boyacá" },
  { city: "La Victoria", department: "Boyacá" },
  { city: "Macanal", department: "Boyacá" },
  { city: "Maripí", department: "Boyacá" },
  { city: "Miraflores", department: "Boyacá" },
  { city: "Mongua", department: "Boyacá" },
  { city: "Monguí", department: "Boyacá" },
  { city: "Moniquirá", department: "Boyacá" },
  { city: "Muzo", department: "Boyacá" },
  { city: "Nobsa", department: "Boyacá" },
  { city: "Nuevo Colón", department: "Boyacá" },
  { city: "Oicatá", department: "Boyacá" },
  { city: "Otanche", department: "Boyacá" },
  { city: "Pachavita", department: "Boyacá" },
  { city: "Páez", department: "Boyacá" },
  { city: "Paipa", department: "Boyacá" },
  { city: "Pajarito", department: "Boyacá" },
  { city: "Panqueba", department: "Boyacá" },
  { city: "Pauna", department: "Boyacá" },
  { city: "Paya", department: "Boyacá" },
  { city: "Pesca", department: "Boyacá" },
  { city: "Pisba", department: "Boyacá" },
  { city: "Puerto Boyacá", department: "Boyacá" },
  { city: "Quípama", department: "Boyacá" },
  { city: "Ramiriquí", department: "Boyacá" },
  { city: "Ráquira", department: "Boyacá" },
  { city: "Rondón", department: "Boyacá" },
  { city: "Saboyá", department: "Boyacá" },
  { city: "Sáchica", department: "Boyacá" },
  { city: "Samacá", department: "Boyacá" },
  { city: "San Eduardo", department: "Boyacá" },
  { city: "San Mateo", department: "Boyacá" },
  { city: "Santana", department: "Boyacá" },
  { city: "Santa María", department: "Boyacá" },
  { city: "Santa Sofía", department: "Boyacá" },
  { city: "Sativanorte", department: "Boyacá" },
  { city: "Sativasur", department: "Boyacá" },
  { city: "Siachoque", department: "Boyacá" },
  { city: "Soatá", department: "Boyacá" },
  { city: "Socotá", department: "Boyacá" },
  { city: "Socha", department: "Boyacá" },
  { city: "Sogamoso", department: "Boyacá" },
  { city: "Somondoco", department: "Boyacá" },
  { city: "Sora", department: "Boyacá" },
  { city: "Sotaquirá", department: "Boyacá" },
  { city: "Soracá", department: "Boyacá" },
  { city: "Susacón", department: "Boyacá" },
  { city: "Sutamarchán", department: "Boyacá" },
  { city: "Sutatenza", department: "Boyacá" },
  { city: "Tasco", department: "Boyacá" },
  { city: "Tenza", department: "Boyacá" },
  { city: "Tibaná", department: "Boyacá" },
  { city: "Tinjacá", department: "Boyacá" },
  { city: "Tipacoque", department: "Boyacá" },
  { city: "Toca", department: "Boyacá" },
  { city: "Tópaga", department: "Boyacá" },
  { city: "Tota", department: "Boyacá" },
  { city: "Turmequé", department: "Boyacá" },
  { city: "Tutazá", department: "Boyacá" },
  { city: "Umbita", department: "Boyacá" },
  { city: "Ventaquemada", department: "Boyacá" },
  { city: "Viracachá", department: "Boyacá" },
  { city: "Zetaquira", department: "Boyacá" },
  { city: "Manizales", department: "Caldas" },
  { city: "Aguadas", department: "Caldas" },
  { city: "Anserma", department: "Caldas" },
  { city: "Aranzazu", department: "Caldas" },
  { city: "Belalcázar", department: "Caldas" },
  { city: "Chinchiná", department: "Caldas" },
  { city: "Filadelfia", department: "Caldas" },
  { city: "La Dorada", department: "Caldas" },
  { city: "La Merced", department: "Caldas" },
  { city: "Manzanares", department: "Caldas" },
  { city: "Marmato", department: "Caldas" },
  { city: "Marulanda", department: "Caldas" },
  { city: "Neira", department: "Caldas" },
  { city: "Norcasia", department: "Caldas" },
  { city: "Pácora", department: "Caldas" },
  { city: "Palestina", department: "Caldas" },
  { city: "Pensilvania", department: "Caldas" },
  { city: "Riosucio", department: "Caldas" },
  { city: "Risaralda", department: "Caldas" },
  { city: "Salamina", department: "Caldas" },
  { city: "Samaná", department: "Caldas" },
  { city: "San José", department: "Caldas" },
  { city: "Supía", department: "Caldas" },
  { city: "Victoria", department: "Caldas" },
  { city: "Villamaría", department: "Caldas" },
  { city: "Viterbo", department: "Caldas" },
  { city: "Florencia", department: "Caquetá" },
  { city: "Albania", department: "Caquetá" },
  { city: "Curillo", department: "Caquetá" },
  { city: "El Doncello", department: "Caquetá" },
  { city: "El Paujil", department: "Caquetá" },
  { city: "Morelia", department: "Caquetá" },
  { city: "Puerto Rico", department: "Caquetá" },
  { city: "Solano", department: "Caquetá" },
  { city: "Solita", department: "Caquetá" },
  { city: "Valparaíso", department: "Caquetá" },
  { city: "Popayán", department: "Cauca" },
  { city: "Almaguer", department: "Cauca" },
  { city: "Argelia", department: "Cauca" },
  { city: "Balboa", department: "Cauca" },
  { city: "Bolívar", department: "Cauca" },
  { city: "Buenos Aires", department: "Cauca" },
  { city: "Cajibío", department: "Cauca" },
  { city: "Caldono", department: "Cauca" },
  { city: "Caloto", department: "Cauca" },
  { city: "Corinto", department: "Cauca" },
  { city: "El Tambo", department: "Cauca" },
  { city: "Florencia", department: "Cauca" },
  { city: "Guachené", department: "Cauca" },
  { city: "Guapi", department: "Cauca" },
  { city: "Inzá", department: "Cauca" },
  { city: "Jambaló", department: "Cauca" },
  { city: "La Sierra", department: "Cauca" },
  { city: "La Vega", department: "Cauca" },
  { city: "López", department: "Cauca" },
  { city: "Mercaderes", department: "Cauca" },
  { city: "Miranda", department: "Cauca" },
  { city: "Morales", department: "Cauca" },
  { city: "Padilla", department: "Cauca" },
  { city: "Patía", department: "Cauca" },
  { city: "Piamonte", department: "Cauca" },
  { city: "Piendamó", department: "Cauca" },
  { city: "Puerto Tejada", department: "Cauca" },
  { city: "Puracé", department: "Cauca" },
  { city: "Rosas", department: "Cauca" },
  { city: "Santa Rosa", department: "Cauca" },
  { city: "Silvia", department: "Cauca" },
  { city: "Sotara", department: "Cauca" },
  { city: "Suárez", department: "Cauca" },
  { city: "Sucre", department: "Cauca" },
  { city: "Timbío", department: "Cauca" },
  { city: "Timbiquí", department: "Cauca" },
  { city: "Toribio", department: "Cauca" },
  { city: "Totoró", department: "Cauca" },
  { city: "Villa Rica", department: "Cauca" },
  { city: "Valledupar", department: "Cesar" },
  { city: "Aguachica", department: "Cesar" },
  { city: "Agustín Codazzi", department: "Cesar" },
  { city: "Astrea", department: "Cesar" },
  { city: "Becerril", department: "Cesar" },
  { city: "Bosconia", department: "Cesar" },
  { city: "Chimichagua", department: "Cesar" },
  { city: "Chiriguaná", department: "Cesar" },
  { city: "Curumaní", department: "Cesar" },
  { city: "El Copey", department: "Cesar" },
  { city: "El Paso", department: "Cesar" },
  { city: "Gamarra", department: "Cesar" },
  { city: "González", department: "Cesar" },
  { city: "La Gloria", department: "Cesar" },
  { city: "Manaure", department: "Cesar" },
  { city: "Pailitas", department: "Cesar" },
  { city: "Pelaya", department: "Cesar" },
  { city: "Pueblo Bello", department: "Cesar" },
  { city: "La Paz", department: "Cesar" },
  { city: "San Alberto", department: "Cesar" },
  { city: "San Diego", department: "Cesar" },
  { city: "San Martín", department: "Cesar" },
  { city: "Tamalameque", department: "Cesar" },
  { city: "Montería", department: "Córdoba" },
  { city: "Ayapel", department: "Córdoba" },
  { city: "Buenavista", department: "Córdoba" },
  { city: "Canalete", department: "Córdoba" },
  { city: "Cereté", department: "Córdoba" },
  { city: "Chimá", department: "Córdoba" },
  { city: "Chinú", department: "Córdoba" },
  { city: "Cotorra", department: "Córdoba" },
  { city: "Lorica", department: "Córdoba" },
  { city: "Los Córdobas", department: "Córdoba" },
  { city: "Momil", department: "Córdoba" },
  { city: "Moñitos", department: "Córdoba" },
  { city: "Planeta Rica", department: "Córdoba" },
  { city: "Pueblo Nuevo", department: "Córdoba" },
  { city: "Puerto Escondido", department: "Córdoba" },
  { city: "Purísima", department: "Córdoba" },
  { city: "Sahagún", department: "Córdoba" },
  { city: "San Andrés Sotavento", department: "Córdoba" },
  { city: "San Antero", department: "Córdoba" },
  { city: "San Pelayo", department: "Córdoba" },
  { city: "Tierralta", department: "Córdoba" },
  { city: "Tuchín", department: "Córdoba" },
  { city: "Valencia", department: "Córdoba" },
  { city: "Anapoima", department: "Cundinamarca" },
  { city: "Arbeláez", department: "Cundinamarca" },
  { city: "Beltrán", department: "Cundinamarca" },
  { city: "Bituima", department: "Cundinamarca" },
  { city: "Bojacá", department: "Cundinamarca" },
  { city: "Cabrera", department: "Cundinamarca" },
  { city: "Cachipay", department: "Cundinamarca" },
  { city: "Cajicá", department: "Cundinamarca" },
  { city: "Caparrapí", department: "Cundinamarca" },
  { city: "Caqueza", department: "Cundinamarca" },
  { city: "Chaguaní", department: "Cundinamarca" },
  { city: "Chipaque", department: "Cundinamarca" },
  { city: "Choachí", department: "Cundinamarca" },
  { city: "Chocontá", department: "Cundinamarca" },
  { city: "Cogua", department: "Cundinamarca" },
  { city: "Cota", department: "Cundinamarca" },
  { city: "Cucunubá", department: "Cundinamarca" },
  { city: "El Colegio", department: "Cundinamarca" },
  { city: "El Rosal", department: "Cundinamarca" },
  { city: "Fomeque", department: "Cundinamarca" },
  { city: "Fosca", department: "Cundinamarca" },
  { city: "Funza", department: "Cundinamarca" },
  { city: "Fúquene", department: "Cundinamarca" },
  { city: "Gachala", department: "Cundinamarca" },
  { city: "Gachancipá", department: "Cundinamarca" },
  { city: "Gachetá", department: "Cundinamarca" },
  { city: "Girardot", department: "Cundinamarca" },
  { city: "Granada", department: "Cundinamarca" },
  { city: "Guachetá", department: "Cundinamarca" },
  { city: "Guaduas", department: "Cundinamarca" },
  { city: "Guasca", department: "Cundinamarca" },
  { city: "Guataquí", department: "Cundinamarca" },
  { city: "Guatavita", department: "Cundinamarca" },
  { city: "Guayabetal", department: "Cundinamarca" },
  { city: "Gutiérrez", department: "Cundinamarca" },
  { city: "Jerusalén", department: "Cundinamarca" },
  { city: "Junín", department: "Cundinamarca" },
  { city: "La Calera", department: "Cundinamarca" },
  { city: "La Mesa", department: "Cundinamarca" },
  { city: "La Palma", department: "Cundinamarca" },
  { city: "La Peña", department: "Cundinamarca" },
  { city: "La Vega", department: "Cundinamarca" },
  { city: "Lenguazaque", department: "Cundinamarca" },
  { city: "Macheta", department: "Cundinamarca" },
  { city: "Madrid", department: "Cundinamarca" },
  { city: "Manta", department: "Cundinamarca" },
  { city: "Medina", department: "Cundinamarca" },
  { city: "Mosquera", department: "Cundinamarca" },
  { city: "Nariño", department: "Cundinamarca" },
  { city: "Nemocón", department: "Cundinamarca" },
  { city: "Nilo", department: "Cundinamarca" },
  { city: "Nimaima", department: "Cundinamarca" },
  { city: "Nocaima", department: "Cundinamarca" },
  { city: "Venecia", department: "Cundinamarca" },
  { city: "Pacho", department: "Cundinamarca" },
  { city: "Paime", department: "Cundinamarca" },
  { city: "Pandi", department: "Cundinamarca" },
  { city: "Paratebueno", department: "Cundinamarca" },
  { city: "Pasca", department: "Cundinamarca" },
  { city: "Puerto Salgar", department: "Cundinamarca" },
  { city: "Pulí", department: "Cundinamarca" },
  { city: "Quebradanegra", department: "Cundinamarca" },
  { city: "Quetame", department: "Cundinamarca" },
  { city: "Quipile", department: "Cundinamarca" },
  { city: "Apulo", department: "Cundinamarca" },
  { city: "Ricaurte", department: "Cundinamarca" },
  { city: "San Bernardo", department: "Cundinamarca" },
  { city: "San Cayetano", department: "Cundinamarca" },
  { city: "San Francisco", department: "Cundinamarca" },
  { city: "Sesquilé", department: "Cundinamarca" },
  { city: "Sibaté", department: "Cundinamarca" },
  { city: "Silvania", department: "Cundinamarca" },
  { city: "Simijaca", department: "Cundinamarca" },
  { city: "Soacha", department: "Cundinamarca" },
  { city: "Subachoque", department: "Cundinamarca" },
  { city: "Suesca", department: "Cundinamarca" },
  { city: "Supatá", department: "Cundinamarca" },
  { city: "Susa", department: "Cundinamarca" },
  { city: "Sutatausa", department: "Cundinamarca" },
  { city: "Tabio", department: "Cundinamarca" },
  { city: "Tausa", department: "Cundinamarca" },
  { city: "Tena", department: "Cundinamarca" },
  { city: "Tenjo", department: "Cundinamarca" },
  { city: "Tibacuy", department: "Cundinamarca" },
  { city: "Tibirita", department: "Cundinamarca" },
  { city: "Tocaima", department: "Cundinamarca" },
  { city: "Tocancipá", department: "Cundinamarca" },
  { city: "Topaipí", department: "Cundinamarca" },
  { city: "Ubalá", department: "Cundinamarca" },
  { city: "Ubaque", department: "Cundinamarca" },
  { city: "Une", department: "Cundinamarca" },
  { city: "Útica", department: "Cundinamarca" },
  { city: "Vianí", department: "Cundinamarca" },
  { city: "Villagómez", department: "Cundinamarca" },
  { city: "Villapinzón", department: "Cundinamarca" },
  { city: "Villeta", department: "Cundinamarca" },
  { city: "Viotá", department: "Cundinamarca" },
  { city: "Zipacón", department: "Cundinamarca" },
  { city: "Quibdó", department: "Chocó" },
  { city: "Acandí", department: "Chocó" },
  { city: "Alto Baudo", department: "Chocó" },
  { city: "Atrato", department: "Chocó" },
  { city: "Bagadó", department: "Chocó" },
  { city: "Bahía Solano", department: "Chocó" },
  { city: "Bajo Baudó", department: "Chocó" },
  { city: "Bojaya", department: "Chocó" },
  { city: "Cértegui", department: "Chocó" },
  { city: "Condoto", department: "Chocó" },
  { city: "Juradó", department: "Chocó" },
  { city: "Lloró", department: "Chocó" },
  { city: "Medio Atrato", department: "Chocó" },
  { city: "Medio Baudó", department: "Chocó" },
  { city: "Medio San Juan", department: "Chocó" },
  { city: "Nóvita", department: "Chocó" },
  { city: "Nuquí", department: "Chocó" },
  { city: "Río Iro", department: "Chocó" },
  { city: "Río Quito", department: "Chocó" },
  { city: "Riosucio", department: "Chocó" },
  { city: "Sipí", department: "Chocó" },
  { city: "Unguía", department: "Chocó" },
  { city: "Neiva", department: "Huila" },
  { city: "Acevedo", department: "Huila" },
  { city: "Agrado", department: "Huila" },
  { city: "Aipe", department: "Huila" },
  { city: "Algeciras", department: "Huila" },
  { city: "Altamira", department: "Huila" },
  { city: "Baraya", department: "Huila" },
  { city: "Campoalegre", department: "Huila" },
  { city: "Colombia", department: "Huila" },
  { city: "Elías", department: "Huila" },
  { city: "Garzón", department: "Huila" },
  { city: "Gigante", department: "Huila" },
  { city: "Guadalupe", department: "Huila" },
  { city: "Hobo", department: "Huila" },
  { city: "Iquira", department: "Huila" },
  { city: "Isnos", department: "Huila" },
  { city: "La Argentina", department: "Huila" },
  { city: "La Plata", department: "Huila" },
  { city: "Nátaga", department: "Huila" },
  { city: "Oporapa", department: "Huila" },
  { city: "Paicol", department: "Huila" },
  { city: "Palermo", department: "Huila" },
  { city: "Palestina", department: "Huila" },
  { city: "Pital", department: "Huila" },
  { city: "Pitalito", department: "Huila" },
  { city: "Rivera", department: "Huila" },
  { city: "Saladoblanco", department: "Huila" },
  { city: "Santa María", department: "Huila" },
  { city: "Suaza", department: "Huila" },
  { city: "Tarqui", department: "Huila" },
  { city: "Tesalia", department: "Huila" },
  { city: "Tello", department: "Huila" },
  { city: "Teruel", department: "Huila" },
  { city: "Timaná", department: "Huila" },
  { city: "Villavieja", department: "Huila" },
  { city: "Yaguará", department: "Huila" },
  { city: "Riohacha", department: "La Guajira" },
  { city: "Albania", department: "La Guajira" },
  { city: "Barrancas", department: "La Guajira" },
  { city: "Dibula", department: "La Guajira" },
  { city: "Distracción", department: "La Guajira" },
  { city: "El Molino", department: "La Guajira" },
  { city: "Fonseca", department: "La Guajira" },
  { city: "Hatonuevo", department: "La Guajira" },
  { city: "Maicao", department: "La Guajira" },
  { city: "Manaure", department: "La Guajira" },
  { city: "Uribia", department: "La Guajira" },
  { city: "Urumita", department: "La Guajira" },
  { city: "Villanueva", department: "La Guajira" },
  { city: "Santa Marta", department: "Magdalena" },
  { city: "Algarrobo", department: "Magdalena" },
  { city: "Aracataca", department: "Magdalena" },
  { city: "Ariguaní", department: "Magdalena" },
  { city: "Cerro San Antonio", department: "Magdalena" },
  { city: "Chivolo", department: "Magdalena" },
  { city: "Concordia", department: "Magdalena" },
  { city: "El Banco", department: "Magdalena" },
  { city: "El Piñon", department: "Magdalena" },
  { city: "El Retén", department: "Magdalena" },
  { city: "Fundación", department: "Magdalena" },
  { city: "Guamal", department: "Magdalena" },
  { city: "Nueva Granada", department: "Magdalena" },
  { city: "Pedraza", department: "Magdalena" },
  { city: "Pivijay", department: "Magdalena" },
  { city: "Plato", department: "Magdalena" },
  { city: "Remolino", department: "Magdalena" },
  { city: "Salamina", department: "Magdalena" },
  { city: "San Zenón", department: "Magdalena" },
  { city: "Santa Ana", department: "Magdalena" },
  { city: "Sitionuevo", department: "Magdalena" },
  { city: "Tenerife", department: "Magdalena" },
  { city: "Zapayán", department: "Magdalena" },
  { city: "Zona Bananera", department: "Magdalena" },
  { city: "Villavicencio", department: "Meta" },
  { city: "Acacias", department: "Meta" },
  { city: "Cabuyaro", department: "Meta" },
  { city: "Cubarral", department: "Meta" },
  { city: "Cumaral", department: "Meta" },
  { city: "El Calvario", department: "Meta" },
  { city: "El Castillo", department: "Meta" },
  { city: "El Dorado", department: "Meta" },
  { city: "Granada", department: "Meta" },
  { city: "Guamal", department: "Meta" },
  { city: "Mapiripán", department: "Meta" },
  { city: "Mesetas", department: "Meta" },
  { city: "La Macarena", department: "Meta" },
  { city: "Lejanías", department: "Meta" },
  { city: "Puerto Concordia", department: "Meta" },
  { city: "Puerto Gaitán", department: "Meta" },
  { city: "Puerto López", department: "Meta" },
  { city: "Puerto Lleras", department: "Meta" },
  { city: "Puerto Rico", department: "Meta" },
  { city: "Restrepo", department: "Meta" },
  { city: "San Juanito", department: "Meta" },
  { city: "San Martín", department: "Meta" },
  { city: "Vista Hermosa", department: "Meta" },
  { city: "Pasto", department: "Nariño" },
  { city: "Albán", department: "Nariño" },
  { city: "Aldana", department: "Nariño" },
  { city: "Ancuyá", department: "Nariño" },
  { city: "Barbacoas", department: "Nariño" },
  { city: "Colón", department: "Nariño" },
  { city: "Consaca", department: "Nariño" },
  { city: "Contadero", department: "Nariño" },
  { city: "Córdoba", department: "Nariño" },
  { city: "Cuaspud", department: "Nariño" },
  { city: "Cumbal", department: "Nariño" },
  { city: "Cumbitara", department: "Nariño" },
  { city: "El Charco", department: "Nariño" },
  { city: "El Peñol", department: "Nariño" },
  { city: "El Rosario", department: "Nariño" },
  { city: "El Tambo", department: "Nariño" },
  { city: "Funes", department: "Nariño" },
  { city: "Guachucal", department: "Nariño" },
  { city: "Guaitarilla", department: "Nariño" },
  { city: "Gualmatán", department: "Nariño" },
  { city: "Iles", department: "Nariño" },
  { city: "Imués", department: "Nariño" },
  { city: "Ipiales", department: "Nariño" },
  { city: "La Cruz", department: "Nariño" },
  { city: "La Florida", department: "Nariño" },
  { city: "La Llanada", department: "Nariño" },
  { city: "La Tola", department: "Nariño" },
  { city: "La Unión", department: "Nariño" },
  { city: "Leiva", department: "Nariño" },
  { city: "Linares", department: "Nariño" },
  { city: "Los Andes", department: "Nariño" },
  { city: "Magüí", department: "Nariño" },
  { city: "Mallama", department: "Nariño" },
  { city: "Mosquera", department: "Nariño" },
  { city: "Nariño", department: "Nariño" },
  { city: "Olaya Herrera", department: "Nariño" },
  { city: "Ospina", department: "Nariño" },
  { city: "Francisco Pizarro", department: "Nariño" },
  { city: "Policarpa", department: "Nariño" },
  { city: "Potosí", department: "Nariño" },
  { city: "Providencia", department: "Nariño" },
  { city: "Puerres", department: "Nariño" },
  { city: "Pupiales", department: "Nariño" },
  { city: "Ricaurte", department: "Nariño" },
  { city: "Roberto Payán", department: "Nariño" },
  { city: "Samaniego", department: "Nariño" },
  { city: "Sandoná", department: "Nariño" },
  { city: "San Bernardo", department: "Nariño" },
  { city: "San Lorenzo", department: "Nariño" },
  { city: "San Pablo", department: "Nariño" },
  { city: "Santa Bárbara", department: "Nariño" },
  { city: "Sapuyes", department: "Nariño" },
  { city: "Taminango", department: "Nariño" },
  { city: "Tangua", department: "Nariño" },
  { city: "Túquerres", department: "Nariño" },
  { city: "Yacuanquer", department: "Nariño" },
  { city: "Armenia", department: "Quindío" },
  { city: "Buenavista", department: "Quindío" },
  { city: "Circasia", department: "Quindío" },
  { city: "Córdoba", department: "Quindío" },
  { city: "Filandia", department: "Quindío" },
  { city: "La Tebaida", department: "Quindío" },
  { city: "Montenegro", department: "Quindío" },
  { city: "Pijao", department: "Quindío" },
  { city: "Quimbaya", department: "Quindío" },
  { city: "Salento", department: "Quindío" },
  { city: "Pereira", department: "Risaralda" },
  { city: "Apía", department: "Risaralda" },
  { city: "Balboa", department: "Risaralda" },
  { city: "Dosquebradas", department: "Risaralda" },
  { city: "Guática", department: "Risaralda" },
  { city: "La Celia", department: "Risaralda" },
  { city: "La Virginia", department: "Risaralda" },
  { city: "Marsella", department: "Risaralda" },
  { city: "Mistrató", department: "Risaralda" },
  { city: "Pueblo Rico", department: "Risaralda" },
  { city: "Quinchía", department: "Risaralda" },
  { city: "Santuario", department: "Risaralda" },
  { city: "Bucaramanga", department: "Santander" },
  { city: "Aguada", department: "Santander" },
  { city: "Albania", department: "Santander" },
  { city: "Aratoca", department: "Santander" },
  { city: "Barbosa", department: "Santander" },
  { city: "Barichara", department: "Santander" },
  { city: "Barrancabermeja", department: "Santander" },
  { city: "Betulia", department: "Santander" },
  { city: "Bolívar", department: "Santander" },
  { city: "Cabrera", department: "Santander" },
  { city: "California", department: "Santander" },
  { city: "Carcasí", department: "Santander" },
  { city: "Cepitá", department: "Santander" },
  { city: "Cerrito", department: "Santander" },
  { city: "Charalá", department: "Santander" },
  { city: "Charta", department: "Santander" },
  { city: "Chipatá", department: "Santander" },
  { city: "Cimitarra", department: "Santander" },
  { city: "Concepción", department: "Santander" },
  { city: "Confines", department: "Santander" },
  { city: "Contratación", department: "Santander" },
  { city: "Coromoro", department: "Santander" },
  { city: "Curití", department: "Santander" },
  { city: "El Guacamayo", department: "Santander" },
  { city: "El Playón", department: "Santander" },
  { city: "Encino", department: "Santander" },
  { city: "Enciso", department: "Santander" },
  { city: "Florián", department: "Santander" },
  { city: "Floridablanca", department: "Santander" },
  { city: "Galán", department: "Santander" },
  { city: "Gambita", department: "Santander" },
  { city: "Girón", department: "Santander" },
  { city: "Guaca", department: "Santander" },
  { city: "Guadalupe", department: "Santander" },
  { city: "Guapotá", department: "Santander" },
  { city: "Guavatá", department: "Santander" },
  { city: "Güepsa", department: "Santander" },
  { city: "Jesús María", department: "Santander" },
  { city: "Jordán", department: "Santander" },
  { city: "La Belleza", department: "Santander" },
  { city: "Landázuri", department: "Santander" },
  { city: "La Paz", department: "Santander" },
  { city: "Lebríja", department: "Santander" },
  { city: "Los Santos", department: "Santander" },
  { city: "Macaravita", department: "Santander" },
  { city: "Málaga", department: "Santander" },
  { city: "Matanza", department: "Santander" },
  { city: "Mogotes", department: "Santander" },
  { city: "Molagavita", department: "Santander" },
  { city: "Ocamonte", department: "Santander" },
  { city: "Oiba", department: "Santander" },
  { city: "Onzaga", department: "Santander" },
  { city: "Palmar", department: "Santander" },
  { city: "Páramo", department: "Santander" },
  { city: "Piedecuesta", department: "Santander" },
  { city: "Pinchote", department: "Santander" },
  { city: "Puente Nacional", department: "Santander" },
  { city: "Rionegro", department: "Santander" },
  { city: "San Andrés", department: "Santander" },
  { city: "San Gil", department: "Santander" },
  { city: "San Joaquín", department: "Santander" },
  { city: "San Miguel", department: "Santander" },
  { city: "Santa Bárbara", department: "Santander" },
  { city: "Simacota", department: "Santander" },
  { city: "Socorro", department: "Santander" },
  { city: "Suaita", department: "Santander" },
  { city: "Sucre", department: "Santander" },
  { city: "Suratá", department: "Santander" },
  { city: "Tona", department: "Santander" },
  { city: "Vélez", department: "Santander" },
  { city: "Vetas", department: "Santander" },
  { city: "Villanueva", department: "Santander" },
  { city: "Zapatoca", department: "Santander" },
  { city: "Sincelejo", department: "Sucre" },
  { city: "Buenavista", department: "Sucre" },
  { city: "Caimito", department: "Sucre" },
  { city: "Coloso", department: "Sucre" },
  { city: "Coveñas", department: "Sucre" },
  { city: "Chalán", department: "Sucre" },
  { city: "El Roble", department: "Sucre" },
  { city: "Galeras", department: "Sucre" },
  { city: "Guaranda", department: "Sucre" },
  { city: "La Unión", department: "Sucre" },
  { city: "Los Palmitos", department: "Sucre" },
  { city: "Majagual", department: "Sucre" },
  { city: "Morroa", department: "Sucre" },
  { city: "Ovejas", department: "Sucre" },
  { city: "Palmito", department: "Sucre" },
  { city: "San Benito Abad", department: "Sucre" },
  { city: "San Marcos", department: "Sucre" },
  { city: "San Onofre", department: "Sucre" },
  { city: "San Pedro", department: "Sucre" },
  { city: "Sucre", department: "Sucre" },
  { city: "Tolú Viejo", department: "Sucre" },
  { city: "Alpujarra", department: "Tolima" },
  { city: "Alvarado", department: "Tolima" },
  { city: "Ambalema", department: "Tolima" },
  { city: "Armero", department: "Tolima" },
  { city: "Ataco", department: "Tolima" },
  { city: "Cajamarca", department: "Tolima" },
  { city: "Chaparral", department: "Tolima" },
  { city: "Coello", department: "Tolima" },
  { city: "Coyaima", department: "Tolima" },
  { city: "Cunday", department: "Tolima" },
  { city: "Dolores", department: "Tolima" },
  { city: "Espinal", department: "Tolima" },
  { city: "Falan", department: "Tolima" },
  { city: "Flandes", department: "Tolima" },
  { city: "Fresno", department: "Tolima" },
  { city: "Guamo", department: "Tolima" },
  { city: "Herveo", department: "Tolima" },
  { city: "Honda", department: "Tolima" },
  { city: "Icononzo", department: "Tolima" },
  { city: "Mariquita", department: "Tolima" },
  { city: "Melgar", department: "Tolima" },
  { city: "Murillo", department: "Tolima" },
  { city: "Natagaima", department: "Tolima" },
  { city: "Ortega", department: "Tolima" },
  { city: "Palocabildo", department: "Tolima" },
  { city: "Piedras", department: "Tolima" },
  { city: "Planadas", department: "Tolima" },
  { city: "Prado", department: "Tolima" },
  { city: "Purificación", department: "Tolima" },
  { city: "Rio Blanco", department: "Tolima" },
  { city: "Roncesvalles", department: "Tolima" },
  { city: "Rovira", department: "Tolima" },
  { city: "Saldaña", department: "Tolima" },
  { city: "Santa Isabel", department: "Tolima" },
  { city: "Venadillo", department: "Tolima" },
  { city: "Villahermosa", department: "Tolima" },
  { city: "Villarrica", department: "Tolima" },
  { city: "Arauquita", department: "Arauca" },
  { city: "Cravo Norte", department: "Arauca" },
  { city: "Fortul", department: "Arauca" },
  { city: "Puerto Rondón", department: "Arauca" },
  { city: "Saravena", department: "Arauca" },
  { city: "Tame", department: "Arauca" },
  { city: "Arauca", department: "Arauca" },
  { city: "Yopal", department: "Casanare" },
  { city: "Aguazul", department: "Casanare" },
  { city: "Chámeza", department: "Casanare" },
  { city: "Hato Corozal", department: "Casanare" },
  { city: "La Salina", department: "Casanare" },
  { city: "Monterrey", department: "Casanare" },
  { city: "Pore", department: "Casanare" },
  { city: "Recetor", department: "Casanare" },
  { city: "Sabanalarga", department: "Casanare" },
  { city: "Sácama", department: "Casanare" },
  { city: "Tauramena", department: "Casanare" },
  { city: "Trinidad", department: "Casanare" },
  { city: "Villanueva", department: "Casanare" },
  { city: "Mocoa", department: "Putumayo" },
  { city: "Colón", department: "Putumayo" },
  { city: "Orito", department: "Putumayo" },
  { city: "Puerto Caicedo", department: "Putumayo" },
  { city: "Puerto Guzmán", department: "Putumayo" },
  { city: "Leguízamo", department: "Putumayo" },
  { city: "Sibundoy", department: "Putumayo" },
  { city: "San Francisco", department: "Putumayo" },
  { city: "San Miguel", department: "Putumayo" },
  { city: "Santiago", department: "Putumayo" },
  { city: "Leticia", department: "Amazonas" },
  { city: "El Encanto", department: "Amazonas" },
  { city: "La Chorrera", department: "Amazonas" },
  { city: "La Pedrera", department: "Amazonas" },
  { city: "La Victoria", department: "Amazonas" },
  { city: "Puerto Arica", department: "Amazonas" },
  { city: "Puerto Nariño", department: "Amazonas" },
  { city: "Puerto Santander", department: "Amazonas" },
  { city: "Tarapacá", department: "Amazonas" },
  { city: "Inírida", department: "Guainía" },
  { city: "Barranco Minas", department: "Guainía" },
  { city: "Mapiripana", department: "Guainía" },
  { city: "San Felipe", department: "Guainía" },
  { city: "Puerto Colombia", department: "Guainía" },
  { city: "La Guadalupe", department: "Guainía" },
  { city: "Cacahual", department: "Guainía" },
  { city: "Pana Pana", department: "Guainía" },
  { city: "Mitú", department: "Vaupés" },
  { city: "Carurú", department: "Vaupés" },
  { city: "Taraira", department: "Vaupés" },
  { city: "Papunahua", department: "Vaupés" },
  { city: "Yavaraté", department: "Vaupés" },
  { city: "Pacoa", department: "Vaupés" },
  { city: "Morichal", department: "Guainía" },
  { city: "Puerto Carreño", department: "Vichada" },
  { city: "La Primavera", department: "Vichada" },
  { city: "Santa Rosalía", department: "Vichada" },
  { city: "Cumaribo", department: "Vichada" },
  { city: "San José del Fragua", department: "Caquetá" },
  { city: "Barranca de Upía", department: "Meta" },
  { city: "Palmas del Socorro", department: "Santander" },
  { city: "San Juan de Río Seco", department: "Cundinamarca" },
  { city: "Juan de Acosta", department: "Atlántico" },
  { city: "Fuente de Oro", department: "Meta" },
  { city: "San Luis de Gaceno", department: "Casanare" },
  { city: "El Litoral del San Juan", department: "Chocó" },
  { city: "Villa de San Diego de Ubate", department: "Cundinamarca" },
  { city: "Barranco de Loba", department: "Bolívar" },
  { city: "Togüí", department: "Boyacá" },
  { city: "Santa Rosa del Sur", department: "Bolívar" },
  { city: "El Cantón del San Pablo", department: "Chocó" },
  { city: "Villa de Leyva", department: "Boyacá" },
  { city: "San Sebastián de Buenavista", department: "Magdalena" },
  { city: "Paz de Río", department: "Boyacá" },
  { city: "Hatillo de Loba", department: "Bolívar" },
  { city: "Sabanas de San Angel", department: "Magdalena" },
  { city: "Calamar", department: "Guaviare" },
  { city: "Río de Oro", department: "Cesar" },
  { city: "San Pedro de Uraba", department: "Antioquia" },
  { city: "San José del Guaviare", department: "Guaviare" },
  { city: "Santa Rosa de Viterbo", department: "Boyacá" },
  { city: "Santander de Quilichao", department: "Cauca" },
  { city: "Miraflores", department: "Guaviare" },
  { city: "Santafé de Antioquia", department: "Antioquia" },
  { city: "San Carlos de Guaroa", department: "Meta" },
  { city: "Palmar de Varela", department: "Atlántico" },
  { city: "Santa Rosa de Osos", department: "Antioquia" },
  { city: "San Andrés de Cuerquía", department: "Antioquia" },
  { city: "Valle de San Juan", department: "Tolima" },
  { city: "San Vicente de Chucurí", department: "Santander" },
  { city: "San José de Miranda", department: "Santander" },
  {
    city: "Providencia",
    department: "Archipiélago de San Andrés, Providencia y Santa Catalina",
  },
  { city: "Santa Rosa de Cabal", department: "Risaralda" },
  { city: "Guayabal de Siquima", department: "Cundinamarca" },
  { city: "Belén de Los Andaquies", department: "Caquetá" },
  { city: "Paz de Ariporo", department: "Casanare" },
  { city: "Santa Helena del Opón", department: "Santander" },
  { city: "San Pablo de Borbur", department: "Boyacá" },
  { city: "La Jagua del Pilar", department: "La Guajira" },
  { city: "La Jagua de Ibirico", department: "Cesar" },
  { city: "San Luis de Sincé", department: "Sucre" },
  { city: "San Luis de Gaceno", department: "Boyacá" },
  { city: "El Carmen de Bolívar", department: "Bolívar" },
  { city: "El Carmen de Atrato", department: "Chocó" },
  { city: "San Juan de Betulia", department: "Sucre" },
  { city: "Pijiño del Carmen", department: "Magdalena" },
  { city: "Vigía del Fuerte", department: "Antioquia" },
  { city: "San Martín de Loba", department: "Bolívar" },
  { city: "Altos del Rosario", department: "Bolívar" },
  { city: "Carmen de Apicala", department: "Tolima" },
  { city: "San Antonio del Tequendama", department: "Cundinamarca" },
  { city: "Sabana de Torres", department: "Santander" },
  { city: "El Retorno", department: "Guaviare" },
  { city: "San José de Uré", department: "Córdoba" },
  { city: "San Pedro de Cartago", department: "Nariño" },
  { city: "Campo de La Cruz", department: "Atlántico" },
  { city: "San Juan de Arama", department: "Meta" },
  { city: "San José de La Montaña", department: "Antioquia" },
  { city: "Cartagena del Chairá", department: "Caquetá" },
  { city: "San José del Palmar", department: "Chocó" },
  { city: "Agua de Dios", department: "Cundinamarca" },
  { city: "San Jacinto del Cauca", department: "Bolívar" },
  { city: "San Agustín", department: "Huila" },
  { city: "El Tablón de Gómez", department: "Nariño" },
  {
    city: "San Andrés",
    department: "Archipiélago de San Andrés, Providencia y Santa Catalina",
  },
  { city: "San José de Pare", department: "Boyacá" },
  { city: "Valle de Guamez", department: "Putumayo" },
  { city: "San Pablo de Borbur", department: "Bolívar" },
  { city: "Santiago de Tolú", department: "Sucre" },
  { city: "Bogotá D.C.", department: "Bogotá D.C." },
  { city: "Carmen de Carupa", department: "Cundinamarca" },
  { city: "Ciénaga de Oro", department: "Córdoba" },
  { city: "San Juan de Urabá", department: "Antioquia" },
  { city: "San Juan del Cesar", department: "La Guajira" },
  { city: "El Carmen de Chucurí", department: "Santander" },
  { city: "El Carmen de Viboral", department: "Antioquia" },
  { city: "Belén de Umbría", department: "Risaralda" },
  { city: "Belén de Bajira", department: "Chocó" },
  { city: "Valle de San José", department: "Santander" },
  { city: "San Luis", department: "Tolima" },
  { city: "San Miguel de Sema", department: "Boyacá" },
  { city: "San Antonio", department: "Tolima" },
  { city: "San Benito", department: "Santander" },
  { city: "Vergara", department: "Cundinamarca" },
  { city: "San Carlos", department: "Córdoba" },
  { city: "Puerto Alegría", department: "Amazonas" },
  { city: "Hato", department: "Santander" },
  { city: "San Jacinto", department: "Bolívar" },
  { city: "San Sebastián", department: "Cauca" },
  { city: "San Carlos", department: "Antioquia" },
  { city: "Tuta", department: "Boyacá" },
  { city: "Silos", department: "Norte de Santander" },
  { city: "Cácota", department: "Norte de Santander" },
  { city: "El Dovio", department: "Valle del Cauca" },
  { city: "Toledo", department: "Norte de Santander" },
  { city: "Roldanillo", department: "Valle del Cauca" },
  { city: "Mutiscua", department: "Norte de Santander" },
  { city: "Argelia", department: "Valle del Cauca" },
  { city: "El Zulia", department: "Norte de Santander" },
  { city: "Salazar", department: "Norte de Santander" },
  { city: "Sevilla", department: "Valle del Cauca" },
  { city: "Zarzal", department: "Valle del Cauca" },
  { city: "Cucutilla", department: "Norte de Santander" },
  { city: "El Cerrito", department: "Valle del Cauca" },
  { city: "Cartago", department: "Valle del Cauca" },
  { city: "Caicedonia", department: "Valle del Cauca" },
  { city: "Puerto Santander", department: "Norte de Santander" },
  { city: "Gramalote", department: "Norte de Santander" },
  { city: "El Cairo", department: "Valle del Cauca" },
  { city: "El Tarra", department: "Norte de Santander" },
  { city: "La Unión", department: "Valle del Cauca" },
  { city: "Restrepo", department: "Valle del Cauca" },
  { city: "Teorama", department: "Norte de Santander" },
  { city: "Dagua", department: "Valle del Cauca" },
  { city: "Arboledas", department: "Norte de Santander" },
  { city: "Guacarí", department: "Valle del Cauca" },
  { city: "Lourdes", department: "Norte de Santander" },
  { city: "Ansermanuevo", department: "Valle del Cauca" },
  { city: "Bochalema", department: "Norte de Santander" },
  { city: "Bugalagrande", department: "Valle del Cauca" },
  { city: "Convención", department: "Norte de Santander" },
  { city: "Hacarí", department: "Norte de Santander" },
  { city: "La Victoria", department: "Valle del Cauca" },
  { city: "Herrán", department: "Norte de Santander" },
  { city: "Ginebra", department: "Valle del Cauca" },
  { city: "Yumbo", department: "Valle del Cauca" },
  { city: "Obando", department: "Valle del Cauca" },
  { city: "Tibú", department: "Norte de Santander" },
  { city: "San Cayetano", department: "Norte de Santander" },
  { city: "San Calixto", department: "Norte de Santander" },
  { city: "Bolívar", department: "Valle del Cauca" },
  { city: "La Playa", department: "Norte de Santander" },
  { city: "Cali", department: "Valle del Cauca" },
  { city: "San Pedro", department: "Valle del Cauca" },
  { city: "Guadalajara de Buga", department: "Valle del Cauca" },
  { city: "Chinácota", department: "Norte de Santander" },
  { city: "Ragonvalia", department: "Norte de Santander" },
  { city: "La Esperanza", department: "Norte de Santander" },
  { city: "Villa del Rosario", department: "Norte de Santander" },
  { city: "Chitagá", department: "Norte de Santander" },
  { city: "Calima", department: "Valle del Cauca" },
  { city: "Sardinata", department: "Norte de Santander" },
  { city: "Andalucía", department: "Valle del Cauca" },
  { city: "Pradera", department: "Valle del Cauca" },
  { city: "Abrego", department: "Norte de Santander" },
  { city: "Los Patios", department: "Norte de Santander" },
  { city: "Ocaña", department: "Norte de Santander" },
  { city: "Bucarasica", department: "Norte de Santander" },
  { city: "Yotoco", department: "Valle del Cauca" },
  { city: "Palmira", department: "Valle del Cauca" },
  { city: "Riofrío", department: "Valle del Cauca" },
  { city: "Santiago", department: "Norte de Santander" },
  { city: "Alcalá", department: "Valle del Cauca" },
  { city: "Versalles", department: "Valle del Cauca" },
  { city: "Labateca", department: "Norte de Santander" },
  { city: "Cachirá", department: "Norte de Santander" },
  { city: "Villa Caro", department: "Norte de Santander" },
  { city: "Durania", department: "Norte de Santander" },
  { city: "El Águila", department: "Valle del Cauca" },
  { city: "Toro", department: "Valle del Cauca" },
  { city: "Candelaria", department: "Valle del Cauca" },
  { city: "La Cumbre", department: "Valle del Cauca" },
  { city: "Ulloa", department: "Valle del Cauca" },
  { city: "Trujillo", department: "Valle del Cauca" },
  { city: "Vijes", department: "Valle del Cauca" },
  { city: "Chimá", department: "Santander" },
  { city: "Sampués", department: "Sucre" },
  { city: "Nunchía", department: "Casanare" },
  { city: "Pamplona", department: "Norte de Santander" },
  { city: "Albán", department: "Cundinamarca" },
  { city: "Montelíbano", department: "Córdoba" },
  { city: "Puerto Asís", department: "Putumayo" },
  { city: "Corozal", department: "Sucre" },
  { city: "Buesaco", department: "Nariño" },
  { city: "Maní", department: "Casanare" },
  { city: "El Peñón", department: "Bolívar" },
  { city: "Tuluá", department: "Valle del Cauca" },
  { city: "Casabianca", department: "Tolima" },
  { city: "Anolaima", department: "Cundinamarca" },
  { city: "Chía", department: "Cundinamarca" },
  { city: "San Andrés de Tumaco", department: "Nariño" },
  { city: "Milán", department: "Caquetá" },
  { city: "Capitanejo", department: "Santander" },
  { city: "Anzoátegui", department: "Tolima" },
  { city: "Florida", department: "Valle del Cauca" },
  { city: "Repelón", department: "Atlántico" },
  { city: "Frontino", department: "Antioquia" },
  { city: "El Peñón", department: "Cundinamarca" },
  { city: "Pamplonita", department: "Norte de Santander" },
  { city: "Miriti Paraná", department: "Amazonas" },
  { city: "Támara", department: "Casanare" },
  { city: "Tibasosa", department: "Boyacá" },
  { city: "Páez", department: "Cauca" },
  { city: "Ibagué", department: "Tolima" },
  { city: "Puerto Colombia", department: "Atlántico" },
  { city: "Belén", department: "Nariño" },
  { city: "Sopó", department: "Cundinamarca" },
  { city: "Carmen del Darien", department: "Chocó" },
  { city: "Gama", department: "Cundinamarca" },
  { city: "Sasaima", department: "Cundinamarca" },
  { city: "Chachagüí", department: "Nariño" },
  { city: "Cúcuta", department: "Norte de Santander" },
  { city: "Cartagena", department: "Bolívar" },
  { city: "Granada", department: "Antioquia" },
  { city: "Santa Bárbara de Pinto", department: "Magdalena" },
  { city: "María la Baja", department: "Bolívar" },
  { city: "La Montañita", department: "Caquetá" },
  { city: "San Vicente del Caguán", department: "Caquetá" },
  { city: "El Peñón", department: "Santander" },
  { city: "Jardín", department: "Antioquia" },
  { city: "Jamundí", department: "Valle del Cauca" },
  { city: "Tadó", department: "Chocó" },
  { city: "Orocué", department: "Casanare" },
  { city: "Líbano", department: "Tolima" },
  { city: "Yacopí", department: "Cundinamarca" },
  { city: "Calarcá", department: "Quindío" },
  { city: "Sonsón", department: "Antioquia" },
  { city: "El Carmen", department: "Norte de Santander" },
  { city: "Lérida", department: "Tolima" },
  { city: "La Apartada", department: "Córdoba" },
  { city: "San Cristóbal", department: "Bolívar" },
  { city: "Fusagasugá", department: "Cundinamarca" },
  { city: "Zambrano", department: "Bolívar" },
  { city: "La Uvita", department: "Boyacá" },
  { city: "Zipaquirá", department: "Cundinamarca" },
  { city: "Génova", department: "Quindío" },
  { city: "Suárez", department: "Tolima" },
  { city: "Castilla la Nueva", department: "Meta" },
  { city: "Belén", department: "Boyacá" },
  { city: "Unión Panamericana", department: "Chocó" },
  { city: "Pueblo Viejo", department: "Magdalena" },
  { city: "Villagarzón", department: "Putumayo" },
  { city: "Facatativá", department: "Cundinamarca" },
  { city: "Puerto Libertador", department: "Córdoba" },
  { city: "Marquetalia", department: "Caldas" },
  { city: "Arboleda", department: "Nariño" },
  { city: "Buenaventura", department: "Valle del Cauca" },
  { city: "Ciénaga", department: "Magdalena" },
  { city: "Ponedera", department: "Atlántico" },
];

export default function SelectCity({ selectedDepartment, onChange }) {
  return (
    <select
      name="city_birth"
      id="city_birth"
      onChange={onChange}
      className="w-[96%] bg-white border-2 border-darkGray p-3 rounded-full font-medium ml-[0.6rem]"
    >
      <option value=""></option>
      {citys.map((cityList, index) =>
        cityList.department == selectedDepartment ? (
          <option key={index} value={cityList.city}>
            {cityList.city}
          </option>
        ) : null
      )}
    </select>
  );
}
